language: generic
sudo: false

env:
    global:
    - BYOND_MAJOR="513"
    - BYOND_MINOR="1502"
    - NODE_VERSION="4"
    - BUILD_TOOLS=false
    - DM_MAPFILE=""
    matrix:
    - BUILD_TOOLS=true
    - DM_MAPFILE="tgstation2"

cache:
  directories:
    - tgui/node_modules
    - $HOME/BYOND-${BYOND_MAJOR}.${BYOND_MINOR}


addons:
  mariadb: '10.3'
  apt:
    packages:
      - libc6-i386
      - libgcc1:i386
      - libstdc++6:i386
      - libssl-dev:i386
      - pkg-config:i386
      - gcc-multilib
      - "python3"
      - "python3-pip"

node_js:
  - "10"

install:
  - tools/travis/install_build_tools.sh

before_script:
  - tools/travis/before_build_tools.sh
  - tools/travis/before_build_byond.sh

script:
  - tools/travis/check_filedirs.sh tgstation.dme
  - tools/travis/build_tools.sh
  - tools/travis/build_byond.sh

